server:
  port: 80

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090  # http://localhost:9090/api/v1/auth/getpage
          predicates:
            - Path=/auth/**   # gelen isteği yakalar: http://localhost/auth/getpage

        - id: user-service
          uri: http://localhost:9093  # http://localhost:9090/api/v1/user/getpage
          predicates:
            - Path=/userprofile/**   # gelen isteği yakalar: http://localhost/auth/getpage

#     filters:
#       -RewritePath= /ahmetamca/?(?<segment>.*) , api/v1/userporfile/$\{segment}


      default-filters:
        - RewritePath= /(?<segment>.*), /api/v1/$\{segment}

