server:
  port: 9090

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/FacebookAuthDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

my-application:
  jwt:
    secret-key: "X$so*wASwU*!@+ruyOnL9!lchex&fu?@?6e=rO$r$t5-ecrlzuJEml*rAqls4AB6"
    secret-key-env: ${SECRETKEY}