server:
  port: 9093

spring:
  security:
    user:
      name: cenk
      password: root
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: FacebookDB
      username: Java7User
      password: root

my-application:
  redishost: localhost
  jwt:
    secret-key: "X$so*wASwU*!@+ruyOnL9!lchex&fu?@?6e=rO$r$t5-ecrlzuJEml*rAqls4AB6"
    secret-key-env: ${SECRETKEY}
